// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // The Prisma CLI's schema/migration engine can't connect to libsql:// directly,
  // so schema authoring/diffing targets a local SQLite file. The actual Turso
  // database is kept in sync by applying the diffed SQL via `scripts/push-to-turso.mjs`
  // (see package.json "db:push" script), which uses @libsql/client directly.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
